from langchain.agents.agent_types import AgentType
from langchain.chat_models import ChatOpenAI
from langchain.llms import OpenAI
#from langchain.agents.agent_toolkits import create_csv_agent
import os
import validators
import pandas as pd
from rdflib import Graph
import rdflib
from rdflib.namespace import RDF, RDFS
import json

# agent = create_csv_agent(
#     OpenAI(temperature=0),
#     "titanic.csv",
#     verbose=True,
#     agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
# )

def remove_prefix(n):
    if isinstance(n, rdflib.URIRef):
        s = n.split('#')[-1]
        if validators.url(s):
            return s.split('/')[-1]
        return s
    return n


graph = Graph()
graph.parse(location="swade.ttl", format="ttl")
# graph.parse(location="saref4watr.ttl", format="ttl")
# graph.parse(location="saref4city.ttl", format="ttl")
# print(graph)

classes_tmp = ""
objects = []

for sub, pred, obj in graph:
    sub = remove_prefix(sub)
    pred = remove_prefix(pred)
    obj = remove_prefix(obj)

    #objects.append(obj)
    #objects.extend(obj.split(','))
    #for index, value in obj.split(','):
    #    print(f"{index}: {value}")
    #print(len(obj.split(',')))
    print(obj)

    # TODO - filter duplicates
    # LET'S CONSIDER THESE VALUES (OBJ LIST) AS THE CLASS NAMES TO APSS TO THE LLM
    # IF IT HAS "HAS" AS A PREFIX, REMOVE IT

#print(objects)

"""
for sub, pred, obj in graph:
    if pred == RDF.type and obj == RDFS.Class:
        print(f"Class: {sub}")
"""
#print(classes_tmp)

"""
qres = graph.query(
    "SELECT DISTINCT ?class WHERE { ?class a rdfs:Class . }"
)

for row in qres:
    print(f"Class: {row}")
"""

base_filepath = "/Users/malikluti/Documents/MyProjects/SWADE/SWADE_Project/Data_Samples"
city_a_csv = os.path.join(base_filepath, 'city_A.csv')
city_b_csv = os.path.join(base_filepath, 'city_B.csv')

city_a_content = pd.read_csv(city_a_csv)
#print(city_a_content.iloc[0])

def get_column_names(pandas_input):
    return pandas_input.columns.tolist()

city_a_column_names = get_column_names(city_a_content)
#print(city_a_content.iloc[0].tolist())

city_a_json = []

for row_index in range(city_a_content.shape[0]):
    current_row = []

    for index, raw_item in enumerate(city_a_content.iloc[row_index].tolist()):
        current_row_json = {
            "original_column_name": None,
            "original_item_value": None,
            "ontology_class_name": None,
            "ontology_instance_value": None
        }
        current_row_json["original_column_name"] = city_a_column_names[index]
        current_row_json["original_item_value"] = raw_item

        current_row.append(current_row_json)

    city_a_json.append(current_row)

#print(city_a_json)

1 # LLM FINDING THE MATCH BETWEEN THE CLASSES AND THE ORIGINAL CSV NAMES
2 # SET THE NAME OF THE GRAPH CLASSES TO THE JSON OBJECT (ontology_class_name)
3 # LLM GENERATE A PYTHON FUNCTION PER CLASS THAT TURNS THE DATA FROM THE original_item_value format to ontology_instance_value format
4 # LLM GENERTAE THE EXPECTED OUTPUT FROM 5 ROWS
5 # TEST THE FUNCTION GENERATED BY STEP 3 WITH THE TEST SET GENERATED BY STEP 4
6 # ITERATE STEPS 3, 4, 5 FOR EVERY COLUMN IN THE ORIGINAL CSV/JSON FILE
7 # EXECUTE THE PYTHON FUNCTIONS OVER EVERY ROW OF THE JSON OBJECT

"""
funct 1 - col 1
funct 2 - col 2
"""
"" \
"def turn_date_into_ontology_date(date):" \
#"" datetime dateimt\
#    reutnr ontology_instance_value
""

"""
original_item_value: '63
ontology_instance_value: 1963
"""


"""
agent = create_csv_agent(
    ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613", ),
    city_a,
    verbose=True,
    agent_type=AgentType.OPENAI_FUNCTIONS,
)

agent.run("how many rows are there in the file?")
"""

# new code
swade = NameSpace("http://www.semanticweb.org/malikluti/ontologies/swade")
query = prepareQuery("""
	SELECT ?code 
	where
	{
   		?x a swade:Material .
   		?x swade:code ?code .
	}
	""", initNs={'swade': swade})

# Execute the query
results = gx.query(query)
print(results)
# Print the results
for res in results:
    print(f"{res['material']}")
    if df['material'] == res['material']:
        ! pip
        install
        rdflib
        ! pip
        install
        rdflib - jsonld
        !
        ! pip
        install
        pydotplus
        ! pip
        install
        graphviz